#!/usr/bin/env python3
"""Generate the Python-PoC figure data files from results/results_<family>_<size>.csv.

Emits, for each family (synth, gmark, mol), the \\addplot bodies consumed by the
standalone figure shells in the paper's figures/ directory:

  figures/_data/poc_states_<family>_data.tex    (ovstates_*:  states_med,   log axis)
  figures/_data/poc_prune_<family>_data.tex     (ovprune_*:   prune_rate)
  figures/_data/poc_ablation_<family>_data.tex  (ablation_*:  states_med, VF2-Prob variants only)
  figures/_data/poc_loglik_<family>_data.tex    (loglik_*:    best_loglik_med, VF2-Prob variants only)
  figures/_data/poc_runtime_<family>_data.tex   (runtime_*:   median_ms with IQR whiskers)

The figure shells keep the axis setup (symbolic coords, ranges, legends); only the
data move. Axis ranges in the shells are static — after a re-run with very
different magnitudes, check that no bar is clipped.

The ML detail figures (ml_recovery, ml_ece, mldetail_*) are seeded from the
train_weights app instead: its stdout reports the accuracy/ECE summary and it
writes results/reliability.csv; they are small enough to update by hand.

Usage: PAPER_DIR=<paper TeX dir> python3 scripts/make_poc_figures.py
(default PAPER_DIR: <repo>/paper)
"""
import argparse
import csv
import math
import os
import sys
from pathlib import Path

HEADER = "% Generated by scripts/make_poc_figures.py — do not edit.\n"

FAMILIES = ["synth", "gmark", "mol"]
SIZES = ["S", "M", "L"]
SIZE_STYLE = {"S": "sblue", "M": "sorange", "L": "sgreen"}

# axis label -> method name in the CSVs
ALL_METHODS = [
    ("VF2", "vf2"), ("VF2++", "vf2pp"), ("Bin", "vf2bin"),
    ("Dn", "vf2prob"), ("Da", "vf2prob-assign"),
    ("An", "vf2prob-astar"), ("Aa", "vf2prob-astar-assign"),
]
PROB_METHODS = ALL_METHODS[3:]

# (kind, family) pairs whose data files carry inline \addlegendentry per size
# (each figure row shows the legend on exactly one panel)
LEGEND = {("states", "gmark"), ("ablation", "synth"),
          ("loglik", "synth"), ("runtime", "gmark")}


def load(results, family, size):
    path = results / f"results_{family}_{size}.csv"
    if not path.exists():
        return None
    with open(path) as f:
        return {r["method"]: r for r in csv.DictReader(f)}


def num(row, col):
    try:
        v = float(row[col])
        return None if math.isnan(v) else v
    except (KeyError, TypeError, ValueError):
        return None


def fmt(v):
    if v is None:
        return None
    if abs(v) >= 1e4:
        return f"{v:.4g}"
    return f"{v:g}"


def coord_plots(per_size, methods, col, legend):
    """One \\addplot per size over symbolic method coords; skips missing cells."""
    lines = []
    for s in SIZES:
        rows = per_size.get(s)
        if rows is None:
            continue
        pts = []
        for label, m in methods:
            v = fmt(num(rows.get(m, {}), col))
            if v is not None:
                pts.append(f"({label},{v})")
        lines.append(f"\\addplot[{SIZE_STYLE[s]}] coordinates {{{''.join(pts)}}};")
        if legend:
            lines.append(f"\\addlegendentry{{{s}}}")
    return lines


def runtime_plots(per_size, legend, floor_ms=0.1):
    """Median wall-clock bars with IQR whiskers; the lower whisker is clamped at
    the log-axis floor (a symmetric median±IQR would extend below zero)."""
    lines = []
    for s in SIZES:
        rows = per_size.get(s)
        if rows is None:
            continue
        tab = ["m,med,ep,em"]
        for label, m in ALL_METHODS:
            med = num(rows.get(m, {}), "median_ms")
            iqr = num(rows.get(m, {}), "iqr_ms") or 0.0
            if med is None:
                continue
            em = min(iqr, max(0.0, med - floor_ms))
            tab.append(f"{label},{med:.6g},{iqr:.6g},{em:.6g}")
        lines.append(
            f"\\addplot[{SIZE_STYLE[s]}, error bars/.cd, y dir=both, y explicit]\n"
            "  table[col sep=comma, header=true, x=m, y=med, y error plus=ep, y error minus=em]{\n"
            + "\n".join(tab) + "\n};")
        if legend:
            lines.append(f"\\addlegendentry{{{s}}}")
    return lines


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default=str(Path(__file__).resolve().parents[1] / "results"))
    ap.add_argument("--paper-dir",
                    default=os.environ.get("PAPER_DIR", str(Path(__file__).resolve().parents[1] / "paper")))
    a = ap.parse_args()
    results = Path(a.results)
    outdir = Path(a.paper_dir) / "figures" / "_data"
    outdir.mkdir(parents=True, exist_ok=True)

    warn = []
    for family in FAMILIES:
        per_size = {s: load(results, family, s) for s in SIZES}
        if all(v is None for v in per_size.values()):
            warn.append(f"results_{family}_* missing — poc_*_{family} data not written")
            continue
        out = {
            f"poc_states_{family}_data.tex": coord_plots(
                per_size, ALL_METHODS, "states_med", ("states", family) in LEGEND),
            f"poc_prune_{family}_data.tex": coord_plots(
                per_size, ALL_METHODS, "prune_rate", ("prune", family) in LEGEND),
            f"poc_ablation_{family}_data.tex": coord_plots(
                per_size, PROB_METHODS, "states_med", ("ablation", family) in LEGEND),
            f"poc_loglik_{family}_data.tex": coord_plots(
                per_size, PROB_METHODS, "best_loglik_med", ("loglik", family) in LEGEND),
            f"poc_runtime_{family}_data.tex": runtime_plots(
                per_size, ("runtime", family) in LEGEND),
        }
        for name, lines in out.items():
            (outdir / name).write_text(HEADER + "\n".join(lines) + "\n")

    for w in warn:
        print(f"warning: {w}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
