#!/usr/bin/env python3
"""Generate the paper's data-driven tables and figure coordinates from results/*.csv."""
import argparse
import csv
import os
import statistics as st
import sys
from pathlib import Path

BUDGET = 200_000  # state budget B
HEADER = "% Generated by scripts/make_paper_data.py — do not edit.\n"

SNAP = [
    ("facebook", "cpp_facebook_{s}.csv"),
    ("ca-HepTh", "cpp_hepth_{s}.csv"),
    ("email-Enron", "cpp_enron_{s}.csv"),
    ("STRING", "cpp_string_{s}.csv"),
]
SNAP_METHODS = ["vf2pp", "mpm", "vf2prob-astar-assign"]
SIZES = ["S", "M", "L"]
MIN_QUERIES = 8


def per_query(rows, method):
    q = {}
    for r in rows:
        if r["method"] != method:
            continue
        q.setdefault(r["query_id"], []).append(r)
    out = {}
    for qid, rs in q.items():
        states = st.median(float(r["states"]) for r in rs)
        ms = st.median(float(r["wall_ns"]) / 1e6 for r in rs)
        complete = all(
            r["timed_out"] == "0" and int(r["solutions"]) >= 1
            and float(r["states"]) <= BUDGET
            for r in rs
        )
        out[qid] = {"states": states, "ms": ms, "complete": complete}
    return out


def load_csv(path):
    if not path.exists():
        return None
    with open(path) as f:
        return list(csv.DictReader(f))


def fmt_states(x):
    if x >= 1e4:
        exp = len(str(int(x))) - 1
        return f"${x / 10**exp:.1f}{{\\times}}10^{{{exp}}}$"
    return f"${x:g}$"


def synthbench(results, outdir, warn):
    rows = load_csv(results / "cpp_synth_M.csv")
    if not rows:
        warn.append("cpp_synth_M.csv missing — synthbench figures not written")
        return
    med = {}
    for m in sorted({r["method"] for r in rows}):
        pq = per_query(rows, m)
        med[m] = (st.median(v["states"] for v in pq.values()),
                  st.median(v["ms"] for v in pq.values()))

    def axis(values, xlabel, xmin, fmt):
        order = sorted(values, key=lambda m: -values[m])
        coords = " ".join(f"({fmt(values[m])},{m})[{fmt(values[m])}]" for m in order)
        return (
            HEADER
            + "\\begin{tikzpicture}\n"
            f"\\begin{{axis}}[xbar, xmode=log, log origin=infty, width=14cm, height=4.7cm, xmin={xmin}, xmax={max(values.values()) * 4:g},\n"
            f"  xlabel={{{xlabel}}},\n"
            f"  symbolic y coords={{{','.join(order)}}},\n"
            "  ytick=data, enlarge y limits=0.10, bar width=5pt,\n"
            "  nodes near coords, nodes near coords style={font=\\footnotesize, anchor=west, xshift=2pt}, point meta=explicit symbolic,\n"
            "  label style={font=\\small}, tick label style={font=\\small}]\n"
            f"\\addplot coordinates {{{coords}}};\n"
            "\\end{axis}\n\\end{tikzpicture}\n"
        )

    (outdir / "synthbench_states_data.tex").write_text(
        axis({m: v[0] for m, v in med.items()}, "median explored states (log)", 8, lambda x: f"{x:g}"))
    (outdir / "synthbench_time_data.tex").write_text(
        axis({m: v[1] for m, v in med.items()}, "median wall-clock time [ms] (log)", 0.003, lambda x: f"{x:.4g}"))


def recovery_fig(results, outdir, warn):
    style = [
        ("vf2prob-learned", "blue,mark=*", "ours (learned)"),
        ("vf2prob-astar-assign", "blue,densely dashed,mark=o", "ours (fixed)"),
        ("vf2bin", "red,mark=square*", "VF2-Bin"),
        ("mpm", "black!60,mark=triangle*", "\\mMPM"),
    ]
    for tag, src in [("synth", "recovery_synth.csv"), ("hepth", "recovery_hepth.csv"),
                     ("mol", "recovery_mol.csv")]:
        rows = load_csv(results / src)
        if not rows:
            warn.append(f"{src} missing — recovery_{tag} figure not written")
            continue
        data = {}
        for r in rows:
            data.setdefault(r["method"], {})[float(r["flip"])] = float(r["accuracy"])
        lines = [HEADER.rstrip("\n")]
        for m, sty, leg in style:
            if m not in data:
                continue
            pts = " ".join(f"({f*100:g},{a:.3f})" for f, a in sorted(data[m].items()))
            lines += [f"\\addplot[{sty}] coordinates {{{pts}}};", f"  \\addlegendentry{{{leg}}}"]
        (outdir / f"recovery_{tag}_data.tex").write_text("\n".join(lines) + "\n")


def recovery_iam(results, outdir, warn):
    rows = load_csv(results / "iam_recovery.csv")
    if not rows:
        warn.append("iam_recovery.csv missing — IAM recovery figure not written")
        return
    data = {}
    for r in rows:
        data.setdefault(r["method"], {})[float(r["flip"])] = float(r["accuracy"])
    style = [
        ("vf2prob-astar-assign", "blue,mark=*", "ours (RBF kernel)"),
        ("vf2pp", "black!60,densely dashed,mark=square*", "VF2++ (structural)"),
    ]
    lines = [HEADER.rstrip("\n")]
    for m, sty, leg in style:
        if m not in data:
            continue
        # x-axis: coordinate-jitter stddev as a percentage of the unit bounding box.
        pts = " ".join(f"({s*100:g},{a:.3f})" for s, a in sorted(data[m].items()))
        lines += [f"\\addplot[{sty}] coordinates {{{pts}}};", f"  \\addlegendentry{{{leg}}}"]
    (outdir / "recovery_iam_data.tex").write_text("\n".join(lines) + "\n")

    # Summary macros so the prose numbers track the CSV exactly.
    def pct(x):
        return f"{round(x * 100)}\\,\\%"
    ours = data.get("vf2prob-astar-assign", {})
    struct = data.get("vf2pp", {})
    macros = [HEADER.rstrip("\n")]
    if 0.0 in ours:
        macros.append(f"\\newcommand{{\\iamOursClean}}{{{pct(ours[0.0])}}}")
    if 0.1 in ours:
        macros.append(f"\\newcommand{{\\iamOursMid}}{{{pct(ours[0.1])}}}")
    if struct:
        base = st.median(struct.values())
        macros.append(f"\\newcommand{{\\iamStructBase}}{{{pct(base)}}}")
        if 0.1 in ours and base > 0:
            macros.append(f"\\newcommand{{\\iamGapMid}}{{{round(ours[0.1] / base)}$\\times$}}")
    (outdir / "iam.tex").write_text("\n".join(macros) + "\n")


def snap_table(results, tables, warn):
    body = []
    for label, pattern in SNAP:
        cells = []
        for s in SIZES:
            path = results / pattern.format(s=s)
            rows = load_csv(path)
            row = []
            if rows is None:
                warn.append(f"{path.name} missing — {label} {s} row is TBD")
                row = ["\\TBD{}"] * 6
            else:
                pq_all = {m: per_query(rows, m) for m in SNAP_METHODS}
                expected = max(len(v) for v in pq_all.values())
                for m in SNAP_METHODS:
                    pq = pq_all[m]
                    if len(pq) < max(MIN_QUERIES, expected):
                        warn.append(f"{path.name}: {m} has {len(pq)}/{expected} queries — TBD")
                        row += ["\\TBD{}", "\\TBD{}"]
                        continue
                    compl = 100.0 * sum(v["complete"] for v in pq.values()) / len(pq)
                    row += [f"{compl:.0f}\\,\\%", fmt_states(st.median(min(v['states'], BUDGET) for v in pq.values()))]
            cells.append((s, row))
        body.append((label, cells))

    out = [HEADER.rstrip("\n"),
           "\\begin{tabular}{llcccccc}", "\\toprule",
           " & & \\multicolumn{2}{c}{VF2++} & \\multicolumn{2}{c}{\\mMPM} & \\multicolumn{2}{c}{\\mVFtwoprobAUB} \\\\",
           "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}",
           "Graph & Size & compl. & states & compl. & states & compl. & states \\\\", "\\midrule"]
    for gi, (label, cells) in enumerate(body):
        for si, (s, rc) in enumerate(cells):
            prefix = f"\\multirow{{3}}{{*}}{{{label}}}" if si == 0 else ""
            out.append(f"{prefix} & {s} & " + " & ".join(rc) + " \\\\")
        if gi < len(body) - 1:
            out.append("\\midrule")
    out += ["\\bottomrule", "\\end{tabular}"]
    (tables / "snap_scalability.tex").write_text("\n".join(out) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default=str(Path(__file__).resolve().parents[1] / "results"))
    ap.add_argument("--paper-dir",
                    default=os.environ.get("PAPER_DIR", str(Path(__file__).resolve().parents[1] / "paper")))
    a = ap.parse_args()
    results, paper = Path(a.results), Path(a.paper_dir)
    outdir, tables = paper / "figures" / "_data", paper / "tables"
    outdir.mkdir(parents=True, exist_ok=True)

    warn = []
    synthbench(results, outdir, warn)
    recovery_fig(results, outdir, warn)
    recovery_iam(results, outdir, warn)
    snap_table(results, tables, warn)
    for w in warn:
        print(f"warning: {w}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
