#!/usr/bin/env python3
"""Emit the assignment-bound fallback-rate macros from a SNAP bench log.

Reads logs produced by `make bench-snap` (each bench echoes its --queries-path and
prints a per-method `assign_fallback=...%`) and writes the \\fb<Graph><Size> macros
into the paper's figures/_data/fallback.tex. Set PAPER_DIR to the paper directory.
"""
import os
import re
import sys
from pathlib import Path

PAPER = Path(os.environ.get("PAPER_DIR", "paper"))
GRAPHS = {"facebook_combined": "Facebook", "email_enron": "Enron", "ca_hepth": "Hepth"}


def parse(logs):
    out = {}
    for path in logs:
        if not Path(path).exists():
            continue
        size = ds = None
        for line in open(path):
            m = re.search(r"queries-path \S+/[\w-]+_([SML])\.json", line)
            if m:
                size = m.group(1)
            m = re.search(r"dataset=(\S+)", line)
            if m:
                ds = m.group(1)
            m = re.search(r"vf2prob-astar-assign:.*assign_fallback=([0-9.]+)%", line)
            if m and ds in GRAPHS and size:
                out[(GRAPHS[ds], size)] = float(m.group(1))
    return out


def main():
    logs = sys.argv[1:] or ["results/bench_snap.log"]
    fb = parse(logs)
    lines = [
        "% Generated by scripts/paper_fallback.py — do not edit.",
        "% Assignment-bound fallback rate (A*+assign variant).",
    ]
    vals = []
    for g in ("Facebook", "Hepth", "Enron"):
        for s in ("S", "M", "L"):
            v = fb.get((g, s))
            if v is None:
                lines.append(f"\\newcommand{{\\fb{g}{s}}}{{\\TBD{{}}}}")
            else:
                lines.append(f"\\newcommand{{\\fb{g}{s}}}{{{v:.0f}\\,\\%}}")
                vals.append(v)
    lines.append(f"\\newcommand{{\\fbMax}}{{{max(vals):.0f}\\,\\%}}" if len(vals) == 9
                 else "\\newcommand{\\fbMax}{\\TBD{}}")
    (PAPER / "figures" / "_data" / "fallback.tex").write_text("\n".join(lines) + "\n")
    for k in sorted(fb):
        print(f"  {k}: {fb[k]:.1f}%")


if __name__ == "__main__":
    main()
